# ----------------------------
# Makefile Options
# ----------------------------

NAME = CP255
ICON = icon.png
DESCRIPTION = "By Mumbojum2"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
